// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8vTE_DxSoKglO-v70vBJ9XWTMiTCx0H0',
    appId: '1:672581368220:android:54c3fb0e33137683113059',
    messagingSenderId: '672581368220',
    projectId: 'to-share-37301',
    storageBucket: 'to-share-37301.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5tNvdaA-jdoQhSBEpNx18XODaKOv-KyM',
    appId: '1:382848135733:ios:c3de789759089e9d6b777c',
    messagingSenderId: '382848135733',
    projectId: 'drive2share-159d9',
    databaseURL:
        'https://drive2share-159d9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'drive2share-159d9.firebasestorage.app',
    iosClientId:
        '382848135733-3747k9hc96hiib33h1onk9ups48u7ggi.apps.googleusercontent.com',
    iosBundleId: 'com.drive2share.app',
  );
}
